### ISSUE TITLE
Database information

### ISSUE THREAD

**Issue by ugintl** [connervieira/Marathon#1]
Where to put database details? Is it using mysql?

**Comment by connervieira** [comment]
Marathon just uses serialized PHP arrays to store information. It saves them to disk inside the 'databases' folder in the root of the project. If you'd like to edit or view this information outside of Marathon, you can do so with a tool like this: https://v0lttech.com/serializededitor.php

Hopefully this helps!

**Comment by ugintl** [comment]
ok thanks. Does this method of saving data has any disadvantages? For e.g security etc etc

**Comment by connervieira** [comment]
The main reason I used PHP's built in functions was just for simplicity. Its drastically more portable and easy to install this way. However, I don't know enough about SQL to give you a sufficient answer on security. As far as I know, both methods are as secure as the device they are stored on. As long as you follow general security practices, Marathon's databases should be more than secure enough for a small business.
